# Generated by Django 4.1.1 on 2022-10-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default='architecture', related_name='posts', to='blog.tag'),
        ),
    ]
